[build]
  command = "npm run build"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express", "serverless-http"]

[[redirects]]
  from = "/ussd"
  to = "/.netlify/functions/ussd"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/ussd"
  status = 200
  force = true
